### ISSUE TITLE
ImportError: No module named serial

### ISSUE THREAD

**Issue by thomasverleye** [shackenberg/text2led.py#1]
Hello,

First of all, thanks for making this possible!
I've found a Velleman MML16CN and I want to modify the text with my macbook Pro.
I've tried out your code, unfortunately I'd never used Python, so now when i try to run the script with the python launcher I get the Import Error "ImportError: No module named serial".

I've been searching over the internet how to fix this and lots of stackoverflows are telling me to install pyserial. I've done that but still won't work, also I don't know which "Interpreter" I have to use? see following image:

![schermafbeelding 2014-11-22 om 18 34 23](https://cloud.githubusercontent.com/assets/2844485/5155018/35ba82aa-7276-11e4-80f2-113ae6324529.png)

Could somebody help me out?

Greetings,

Thomas Verleye

**Comment by shackenberg** [comment]
Hi!

Happy to hear about your interest. First you need to install pip, which is a packet manager for python:
http://stackoverflow.com/questions/17271319/installing-pip-on-mac-os-x

Than you need to install `serial` with `sudo pip install pyserial` than it should work.

Write if you have more questions!
Cheers
Ludwig

**Comment by saurabhwani21** [comment]
Hi Ludwig,

When I tried to use the command you mentioned I am getting an error "sudo not recognized as internal or external command, operable program or batch file."
Could you kindly help.
Thanks.

-Saurabh

**Comment by shackenberg** [comment]
Dear Saurabhwani,

the error message
`sudo not recognized as internal or external command, operable program or batch file.` indicates that you are trying to install the requirements on a Windows system. But they only work for Linux (OSX). I cannot help you with Windows.

Sorry
